"""
Headless Timeline Renderer — ProsAda Burst 09/10/12

Renders a visual snapshot of a ProsAda project's timeline topology to PNG or SVG.
Reuses CanvasLayoutComposer exactly (no layout duplication).

MANAGED ARTIFACT — do not edit manually.
Generated by ProsAda tooling. Refresh via `POST /v2/tooling/refresh`.

Usage:
    python render_timeline.py --project <prosadaRoot> --out output.png
    python render_timeline.py --project <prosadaRoot> --out output.svg --format svg
    python render_timeline.py --project <prosadaRoot> --out output.png --sidecar
    python render_timeline.py --project <prosadaRoot> --out output.png --overlay semantic
    python render_timeline.py --project <prosadaRoot> --out output.png --overlay status
    python render_timeline.py --project <prosadaRoot> --out output.png \\
        --overlay semantic --semantic-kind char --semantic-id joey-valdez
    python render_timeline.py --project <prosadaRoot> --projection-json projection.json

Arguments:
    --project          Path to prosada project directory (contains manifest.json + units/)
    --out              Output file path (default: timeline.png)
    --format           Output format: png (default) or svg
    --sidecar          Write a JSON metadata sidecar alongside --out
    --scope            Only render units reachable from this unitId (subtree filter)
    --streams          Comma-separated stream/thread IDs to include (default: all)
    --status           Only include events with this status label (draft/review/locked)
    --width            Canvas pixel width before margins (default: 1400)
    --scale            Pixels per spine unit (default: 80)
    --title            Optional title text to overlay on the image
    --overlay          Overlay mode: semantic | status | mood | shot
    --semantic-kind    Semantic kind filter for semantic overlay (char/concept/symbol/…)
    --semantic-id      Entity ID filter for semantic overlay (e.g. joey-valdez)
    --projection-json  Path to write the full projection payload JSON
    --prompt-export    Path to write prompt packet export JSON

Exit codes:
    0  Success
    1  Project not found or invalid
    2  No content units to render
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from PIL import Image, ImageDraw, ImageFont

# ---------------------------------------------------------------------------
# Version — used by tooling installer for managed script tracking
# ---------------------------------------------------------------------------
RENDERER_VERSION = "1.3.0"

# ---------------------------------------------------------------------------
# Rendering constants
# ---------------------------------------------------------------------------

LANE_HEIGHT = 36          # px for each lane row
LANE_GAP = 6             # px between lanes
EVENT_HEIGHT = 18         # px for event bars inside a lane
EVENT_Y_OFFSET = 9        # vertical offset to center event in lane
LABEL_FONT_SIZE = 9       # approximate — PIL default font is fixed
MARGIN_LEFT = 120         # room for lane labels on the left
MARGIN_RIGHT = 30
MARGIN_TOP = 50           # room for title/tick marks
MARGIN_BOTTOM = 30
SPINE_TRACK_ALPHA = 60    # timeline track fill alpha (0-255)
THREAD_TRACK_ALPHA = 45
EVENT_ALPHA = 200         # event bar fill alpha
CHECKPOINT_SIZE = 6       # milestone diamond half-size

BG_COLOR = (18, 18, 24)           # dark canvas background
SPINE_COLOR = (80, 80, 100)       # spine timeline track
GRID_COLOR = (35, 35, 50)         # grid lines
TICK_COLOR = (100, 100, 120)      # axis tick marks + labels
LABEL_BG = (0, 0, 0, 160)        # label pill background (RGBA)
LABEL_FG = (220, 220, 230)        # label text color
CHECKPOINT_COLOR = (255, 215, 0)  # milestone diamond (gold)
LOCKED_BORDER = (255, 215, 0)     # locked event border

# Overlay — status tint colors (RGB per narrative.status value)
_STATUS_TINTS: Dict[str, Tuple[int, int, int]] = {
    "draft":  (90,  110, 200),   # blue-indigo
    "review": (210, 150,  40),   # amber
    "locked": (50,  180,  90),   # green
}

# Overlay — semantic highlight + dim
_SEMANTIC_HIGHLIGHT: Tuple[int, int, int] = (0, 200, 220)   # cyan
_SEMANTIC_DIM_OPACITY: float = 0.3

# Overlay — mood tint colors (RGB per first moodTag)
_MOOD_TINTS: Dict[str, Tuple[int, int, int]] = {
    "tense":      (200,  60,  60),  # red
    "wonder":     ( 80, 140, 220),  # blue
    "melancholy": (100,  80, 160),  # purple
    "dread":      ( 60,  40,  90),  # dark violet
    "warmth":     (220, 150,  60),  # amber
    "mystery":    ( 60, 100, 140),  # slate teal
    "hope":       ( 80, 200, 120),  # green
    "unease":     (150, 110,  40),  # muddy gold
}
_MOOD_DEFAULT: Tuple[int, int, int] = (120, 120, 120)  # neutral for unmapped moods
_MOOD_NO_DATA_OPACITY: float = 0.25                     # dim events with no mood

# Overlay — shot type tint + badge abbreviations (RGB per shotType)
_SHOT_TINTS: Dict[str, Tuple[int, int, int]] = {
    "establishing": (220, 180,  60),   # golden — pulling back
    "wide":         (180, 160, 100),   # muted gold
    "aerial":       (120, 200, 240),   # sky blue
    "medium":       (100, 140, 200),   # neutral blue
    "closeup":      (220,  80,  80),   # red — intimate
    "insert":       (200, 120,  60),   # warm detail
    "pov":          ( 80, 200,  80),   # green — character POV
    "cutaway":      (140,  80, 180),   # purple — aside
}
_SHOT_BADGES: Dict[str, str] = {
    "establishing": "EST",
    "wide":         "WID",
    "aerial":       "AER",
    "medium":       "MED",
    "closeup":      "CU",
    "insert":       "INS",
    "pov":          "POV",
    "cutaway":      "CUT",
}
_SHOT_DEFAULT: Tuple[int, int, int] = (100, 100, 100)  # unknown shot type
_SHOT_NO_DATA_OPACITY: float = 0.25                     # dim events with no shot type

# Default palette for streams without a registered color
_DEFAULT_COLORS = [
    "#e91e63", "#9c27b0", "#673ab7", "#3f51b5", "#03a9f4",
    "#00bcd4", "#009688", "#4caf50", "#ff9800", "#ff5722",
]


def _hex_to_rgb(hex_color: str) -> Tuple[int, int, int]:
    h = hex_color.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _lighten(rgb: Tuple[int, int, int], factor: float = 1.5) -> Tuple[int, int, int]:
    return tuple(min(255, int(c * factor)) for c in rgb)  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Scope / stream filter helpers
# ---------------------------------------------------------------------------

def _collect_subtree_ids(
    scope_id: str,
    units: Dict[str, Any],
) -> Set[str]:
    """Return the set of unitIds reachable from scope_id (inclusive)."""
    result: Set[str] = set()

    def _walk(uid: str) -> None:
        if uid in result:
            return
        result.add(uid)
        unit = units.get(uid)
        if unit:
            for child_id in (unit.children or []):
                _walk(child_id)

    _walk(scope_id)
    return result


def _filter_canvas_by_scope(
    canvas: Dict[str, Any],
    scope_ids: Set[str],
) -> Dict[str, Any]:
    """
    Filter events, checkpoints, and optionally timelines/threads to only include
    units within the scope set.

    Event IDs are `ev-{unitId}` or `ev-{unitId}--{streamId}`.
    """
    def _unit_id_from_event_id(ev_id: str) -> Optional[str]:
        if not ev_id.startswith("ev-"):
            return None
        return ev_id[3:].split("--")[0]

    filtered_events = {
        eid: e for eid, e in canvas["events"].items()
        if _unit_id_from_event_id(eid) in scope_ids
    }
    filtered_checkpoints = {
        cid: c for cid, c in canvas["checkpoints"].items()
        if cid.lstrip("cp-") in scope_ids or
           cid[3:] in scope_ids  # cp-{unitId}
    }
    return {
        "timelines": canvas["timelines"],
        "threads": canvas["threads"],
        "events": filtered_events,
        "checkpoints": filtered_checkpoints,
    }


def _filter_canvas_by_streams(
    canvas: Dict[str, Any],
    stream_ids: Set[str],
) -> Dict[str, Any]:
    """Keep only threads whose ID is in stream_ids, and drop their event copies."""
    filtered_threads = {
        tid: t for tid, t in canvas["threads"].items()
        if tid in stream_ids
    }
    # Keep spine events (laneId=0) and stream copies only for included streams
    filtered_events = {
        eid: e for eid, e in canvas["events"].items()
        if e.get("laneId", 0) == 0 or e.get("attachedToId") in stream_ids
    }
    return {
        "timelines": canvas["timelines"],
        "threads": filtered_threads,
        "events": filtered_events,
        "checkpoints": canvas["checkpoints"],
    }


def _filter_canvas_by_status(
    canvas: Dict[str, Any],
    status: str,
) -> Dict[str, Any]:
    """
    Filter events by their isResolved flag.
    status="locked" → only locked (isResolved=True) events.
    status="draft" or "review" → only non-locked events.
    """
    if status == "locked":
        filtered = {eid: e for eid, e in canvas["events"].items() if e.get("isResolved")}
    else:
        filtered = {eid: e for eid, e in canvas["events"].items() if not e.get("isResolved")}
    return {
        "timelines": canvas["timelines"],
        "threads": canvas["threads"],
        "events": filtered,
        "checkpoints": canvas["checkpoints"],
    }


def _apply_canvas_filters(
    canvas: Dict[str, Any],
    units: Dict,
    scope: Optional[str],
    streams: Optional[List[str]],
    status: Optional[str],
) -> Dict[str, Any]:
    """Apply scope/stream/status filters to a composed canvas dict."""
    if scope:
        scope_ids = _collect_subtree_ids(scope, units)
        canvas = _filter_canvas_by_scope(canvas, scope_ids)
    if streams is not None:
        canvas = _filter_canvas_by_streams(canvas, set(streams))
    if status:
        canvas = _filter_canvas_by_status(canvas, status)
    return canvas


# ---------------------------------------------------------------------------
# Overlay infrastructure
# ---------------------------------------------------------------------------

def _overlay_semantic(
    canvas: Dict[str, Any],
    projection: Dict,
    semantic_kind: Optional[str] = None,
    semantic_entity_id: Optional[str] = None,
    **kwargs: Any,
) -> Dict[str, Dict]:
    """
    Semantic entity overlay.

    Matching events (those whose semantic summaries match the kind/entity filter)
    are drawn with a cyan highlight outline at full opacity.
    Non-matching events are dimmed (0.3 opacity).

    With no filter (semantic_kind=None, semantic_entity_id=None):
      events with any semantic refs are highlighted; events with none are dimmed.
    """
    events_payload = {ev["eventId"]: ev for ev in projection.get("events", [])}
    matching_ids: Set[str] = set()

    for ev_id, ev in events_payload.items():
        sem = ev.get("semantic", {})
        if semantic_kind and semantic_entity_id:
            match = (
                sem.get("byKind", {}).get(semantic_kind, 0) > 0
                and semantic_entity_id in sem.get("entityIds", [])
            )
        elif semantic_kind:
            match = sem.get("byKind", {}).get(semantic_kind, 0) > 0
        elif semantic_entity_id:
            match = semantic_entity_id in sem.get("entityIds", [])
        else:
            match = sem.get("refCount", 0) > 0

        if match:
            matching_ids.add(ev_id)

    overlay: Dict[str, Dict] = {}
    has_filter = bool(semantic_kind or semantic_entity_id)
    any_matches = bool(matching_ids)

    for ev_id in canvas.get("events", {}):
        if ev_id in matching_ids:
            overlay[ev_id] = {
                "outline_rgb":   _SEMANTIC_HIGHLIGHT,
                "outline_width": 3,
                "opacity":       1.0,
            }
        elif any_matches or has_filter:
            overlay[ev_id] = {"opacity": _SEMANTIC_DIM_OPACITY}

    return overlay


def _overlay_status(
    canvas: Dict[str, Any],
    projection: Dict,
    **kwargs: Any,
) -> Dict[str, Dict]:
    """
    Execution/status overlay.

    Tints each event bar by its narrative.status:
      draft  → blue-indigo
      review → amber
      locked → green
    """
    ev_status = {
        ev["eventId"]: ev.get("status", "draft")
        for ev in projection.get("events", [])
    }
    overlay: Dict[str, Dict] = {}
    for ev_id in canvas.get("events", {}):
        status = ev_status.get(ev_id, "draft")
        rgb = _STATUS_TINTS.get(status, _STATUS_TINTS["draft"])
        overlay[ev_id] = {"fill_rgb": rgb}
    return overlay


def _overlay_mood(
    canvas: Dict[str, Any],
    projection: Dict,
    **kwargs: Any,
) -> Dict[str, Dict]:
    """
    Presentation mood overlay.

    Tints each event bar by its presentation.moodTags[0] value.
    Events with no presentation data or no moodTags are dimmed.
    Graceful no-op when no units have presentation metadata.
    """
    events_payload = {ev["eventId"]: ev for ev in projection.get("events", [])}
    any_mood = any(
        bool((ev.get("presentation") or {}).get("moodTags"))
        for ev in events_payload.values()
    )

    overlay: Dict[str, Dict] = {}
    for ev_id in canvas.get("events", {}):
        ev = events_payload.get(ev_id, {})
        pres = ev.get("presentation") or {}
        mood_tags = pres.get("moodTags") or []
        first_mood = mood_tags[0].lower() if mood_tags else None

        if first_mood:
            rgb = _MOOD_TINTS.get(first_mood, _MOOD_DEFAULT)
            overlay[ev_id] = {"fill_rgb": rgb, "opacity": 1.0}
        elif any_mood:
            # Dim events that have no mood data when at least some do
            overlay[ev_id] = {"opacity": _MOOD_NO_DATA_OPACITY}

    return overlay


def _overlay_shot(
    canvas: Dict[str, Any],
    projection: Dict,
    **kwargs: Any,
) -> Dict[str, Dict]:
    """
    Presentation shot-type overlay.

    Tints each event bar by its presentation.shotType value and adds a
    short badge text (e.g. 'EST', 'CU', 'POV') rendered inside the bar.
    Events with no shotType are dimmed.
    Graceful no-op when no units have presentation metadata.
    """
    events_payload = {ev["eventId"]: ev for ev in projection.get("events", [])}
    any_shot = any(
        bool((ev.get("presentation") or {}).get("shotType"))
        for ev in events_payload.values()
    )

    overlay: Dict[str, Dict] = {}
    for ev_id in canvas.get("events", {}):
        ev = events_payload.get(ev_id, {})
        pres = ev.get("presentation") or {}
        shot_type = (pres.get("shotType") or "").lower().strip()

        if shot_type:
            rgb = _SHOT_TINTS.get(shot_type, _SHOT_DEFAULT)
            badge = _SHOT_BADGES.get(shot_type, shot_type[:3].upper())
            overlay[ev_id] = {
                "fill_rgb":   rgb,
                "opacity":    1.0,
                "badge_text": badge,
            }
        elif any_shot:
            overlay[ev_id] = {"opacity": _SHOT_NO_DATA_OPACITY}

    return overlay


# Overlay registry — maps overlay name → function
_OVERLAY_REGISTRY: Dict[str, Any] = {
    "semantic": _overlay_semantic,
    "status":   _overlay_status,
    "mood":     _overlay_mood,
    "shot":     _overlay_shot,
}


def compute_overlay(
    overlay_name: str,
    canvas: Dict[str, Any],
    projection: Dict,
    **kwargs: Any,
) -> Dict[str, Dict]:
    """
    Compute overlay data for a canvas + projection pair.

    Parameters
    ----------
    overlay_name : "semantic" | "status" (or any registered name)
    canvas       : composed canvas dict (from CanvasLayoutComposer)
    projection   : projection payload dict (from build_projection)
    **kwargs     : forwarded to the overlay function
                   semantic overlay: semantic_kind=, semantic_entity_id=

    Returns
    -------
    Dict[event_id, overlay_props]
      overlay_props keys (all optional):
        fill_rgb      : (r,g,b) override for event fill
        opacity       : float 0.0..1.0 multiplier for EVENT_ALPHA
        outline_rgb   : (r,g,b) override for event outline
        outline_width : int override for outline stroke width

    Returns empty dict for unknown overlay names (safe no-op).
    """
    fn = _OVERLAY_REGISTRY.get(overlay_name)
    if fn is None:
        return {}
    try:
        return fn(canvas, projection, **kwargs)
    except Exception:
        return {}


# ---------------------------------------------------------------------------
# Core renderer — PNG (PIL)
# ---------------------------------------------------------------------------

class TimelineRenderer:
    """
    Renders a ProsAda canvas layout to a PIL Image.

    Parameters
    ----------
    canvas      : Output of CanvasLayoutComposer.compose()
    scale       : Pixels per spine logical unit (default 80)
    img_width   : Total image width in pixels (auto-sized if None)
    title       : Optional title string overlay
    """

    def __init__(
        self,
        canvas: Dict[str, Any],
        scale: int = 80,
        img_width: Optional[int] = None,
        title: Optional[str] = None,
    ):
        self.canvas = canvas
        self.scale = scale
        self.title = title

        # Compute canvas span from all positioned objects
        max_end = self._compute_max_end()
        content_width = max(int(max_end * scale) + 1, 10)

        self.img_width = img_width if img_width else content_width + MARGIN_LEFT + MARGIN_RIGHT
        self.content_width = self.img_width - MARGIN_LEFT - MARGIN_RIGHT

        # Lane assignment: lane 0 = spine, lanes 1..N = streams
        timelines = canvas.get("timelines", {})
        threads = canvas.get("threads", {})
        self.lane_objects: Dict[int, dict] = {}  # laneId → {id, name, color, position, duration}

        for tl in timelines.values():
            lid = tl.get("laneId", 0)
            self.lane_objects[lid] = {"color": "#4a4a6a", **tl}

        for th in threads.values():
            lid = th.get("laneId", 1)
            self.lane_objects[lid] = th

        max_lane = max(self.lane_objects.keys(), default=0)
        self.num_lanes = max_lane + 1

        # Total image height
        lane_area = self.num_lanes * (LANE_HEIGHT + LANE_GAP)
        self.img_height = MARGIN_TOP + lane_area + MARGIN_BOTTOM

    def _compute_max_end(self) -> float:
        ends: List[float] = [1.0]
        for obj in self.canvas.get("timelines", {}).values():
            ends.append(obj.get("position", 0) + obj.get("duration", 1))
        for obj in self.canvas.get("threads", {}).values():
            ends.append(obj.get("position", 0) + obj.get("duration", 1))
        for obj in self.canvas.get("events", {}).values():
            ends.append(obj.get("position", 0) + obj.get("duration", 1))
        return max(ends)

    def _lane_y(self, lane_id: int) -> int:
        """Top-left y coordinate for the given lane row."""
        return MARGIN_TOP + lane_id * (LANE_HEIGHT + LANE_GAP)

    def _spine_x(self, position: float) -> int:
        """Convert spine logical unit to pixel x (including left margin)."""
        return MARGIN_LEFT + int(position * self.scale)

    def _spine_w(self, duration: float) -> int:
        return max(2, int(duration * self.scale))

    def render(self, overlay_data: Optional[Dict[str, Dict]] = None) -> Image.Image:
        """Produce and return the rendered PIL Image.

        Parameters
        ----------
        overlay_data : Optional per-event overlay props (from compute_overlay).
                       Keys are canvas event ids; values are dicts with optional
                       fill_rgb, opacity, outline_rgb, outline_width.
        """
        img = Image.new("RGB", (self.img_width, self.img_height), BG_COLOR)
        draw = ImageDraw.Draw(img, "RGBA")

        self._draw_grid(draw)
        self._draw_title(draw)
        self._draw_lanes(draw)
        self._draw_events(draw, overlay_data=overlay_data)
        self._draw_checkpoints(draw)
        self._draw_lane_labels(draw)

        return img

    def _draw_grid(self, draw: ImageDraw.ImageDraw) -> None:
        """Draw vertical grid lines at each spine integer unit."""
        max_end = self._compute_max_end()
        for i in range(0, int(max_end) + 2):
            x = self._spine_x(i)
            if x > self.img_width - MARGIN_RIGHT:
                break
            draw.line([(x, MARGIN_TOP), (x, self.img_height - MARGIN_BOTTOM)], fill=GRID_COLOR, width=1)
            # Tick label
            draw.text((x + 2, MARGIN_TOP - 14), str(i), fill=TICK_COLOR)

    def _draw_title(self, draw: ImageDraw.ImageDraw) -> None:
        if not self.title:
            return
        draw.text((MARGIN_LEFT, 8), self.title, fill=LABEL_FG)

    def _draw_lanes(self, draw: ImageDraw.ImageDraw) -> None:
        """Draw timeline/thread track bars (colored background strips)."""
        for lane_id, obj in self.lane_objects.items():
            y = self._lane_y(lane_id)
            pos = obj.get("position", 0)
            dur = obj.get("duration", 1)
            raw_color = obj.get("color", "#888888")

            try:
                rgb = _hex_to_rgb(raw_color)
            except Exception:
                rgb = (128, 128, 128)

            x = self._spine_x(pos)
            w = self._spine_w(dur)

            # Track background
            draw.rectangle(
                [(x, y), (x + w, y + LANE_HEIGHT)],
                fill=rgb + (THREAD_TRACK_ALPHA,),
            )
            # Track border (1px top edge)
            draw.line([(x, y), (x + w, y)], fill=rgb + (180,), width=1)

    def _draw_events(
        self,
        draw: ImageDraw.ImageDraw,
        overlay_data: Optional[Dict[str, Dict]] = None,
    ) -> None:
        """Draw event rectangles on their lanes, applying overlay props per event."""
        od_map = overlay_data or {}

        # Build per-lane color from lane_objects
        lane_colors: Dict[int, Tuple[int, int, int]] = {}
        for lane_id, obj in self.lane_objects.items():
            try:
                lane_colors[lane_id] = _hex_to_rgb(obj.get("color", "#888888"))
            except Exception:
                lane_colors[lane_id] = (128, 128, 128)

        # Sort events so spine (lane 0) renders on top of stream copies
        events_sorted = sorted(
            self.canvas.get("events", {}).values(),
            key=lambda e: (e.get("laneId", 0) != 0),  # lane 0 last (painted on top)
        )

        for event in events_sorted:
            ev_id = event.get("id", "")
            od = od_map.get(ev_id, {})

            lane_id = event.get("laneId", 0)
            y_lane = self._lane_y(lane_id)
            pos = event.get("position", 0)
            dur = event.get("duration", 1)
            is_locked = event.get("isResolved", False)

            # Base color
            base_rgb = lane_colors.get(lane_id, (100, 120, 180))
            light_rgb = _lighten(base_rgb, 1.8)

            # Overlay overrides
            fill_rgb: Tuple[int, int, int] = od.get("fill_rgb", light_rgb)
            opacity: float = od.get("opacity", 1.0)
            outline_rgb: Tuple[int, int, int] = od.get(
                "outline_rgb",
                LOCKED_BORDER if is_locked else light_rgb,
            )
            outline_width: int = od.get("outline_width", 2 if is_locked else 1)

            x = self._spine_x(pos)
            w = self._spine_w(dur)
            y_ev = y_lane + EVENT_Y_OFFSET
            h_ev = EVENT_HEIGHT

            ev_alpha = int(EVENT_ALPHA * opacity)

            # Event fill
            draw.rectangle(
                [(x, y_ev), (x + w, y_ev + h_ev)],
                fill=fill_rgb + (ev_alpha,),
                outline=outline_rgb + (255,),
                width=outline_width,
            )

            # Title label (truncated)
            title = event.get("title", "")
            if title and w > 12:
                max_chars = max(1, (w - 4) // 6)
                label = title[:max_chars] + ("…" if len(title) > max_chars else "")
                draw.text((x + 3, y_ev + 2), label, fill=LABEL_FG)

            # Badge text (e.g. shot type abbreviation from overlay)
            badge = od.get("badge_text")
            if badge and w > 8:
                bw = len(badge) * 6 + 4
                bh = 9
                bx = x + w - bw - 2
                by = y_ev + h_ev - bh - 1
                if bx >= x:
                    draw.rectangle(
                        [(bx, by), (bx + bw, by + bh)],
                        fill=(0, 0, 0, 200),
                    )
                    draw.text((bx + 2, by), badge, fill=(255, 255, 200))

    def _draw_checkpoints(self, draw: ImageDraw.ImageDraw) -> None:
        """Draw milestone diamonds (locked events)."""
        for cp in self.canvas.get("checkpoints", {}).values():
            pos = cp.get("position", 0)
            x = self._spine_x(pos)
            y = self._lane_y(0) + LANE_HEIGHT // 2
            s = CHECKPOINT_SIZE
            # Diamond shape
            draw.polygon(
                [(x, y - s), (x + s, y), (x, y + s), (x - s, y)],
                fill=CHECKPOINT_COLOR,
                outline=(255, 255, 255),
            )

    def _draw_lane_labels(self, draw: ImageDraw.ImageDraw) -> None:
        """Draw lane name labels in the left margin."""
        for lane_id, obj in sorted(self.lane_objects.items()):
            y = self._lane_y(lane_id) + LANE_HEIGHT // 2 - 5
            name = obj.get("name", obj.get("id", f"Lane {lane_id}"))
            # Truncate to fit in margin
            max_chars = (MARGIN_LEFT - 8) // 6
            label = name[:max_chars] if len(name) > max_chars else name
            try:
                rgb = _hex_to_rgb(obj.get("color", "#888888"))
            except Exception:
                rgb = (160, 160, 180)
            draw.text((4, y), label, fill=rgb)


# ---------------------------------------------------------------------------
# SVG renderer
# ---------------------------------------------------------------------------

def _esc(s: str) -> str:
    """XML-escape a string for safe SVG embedding."""
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;")
             .replace("'", "&#x27;"))


class SVGTimelineRenderer:
    """
    SVG output variant of the timeline renderer.

    Geometry is identical to TimelineRenderer (same constants, same lane model).
    Reuses the same canvas dict from CanvasLayoutComposer — no layout duplication.
    """

    def __init__(
        self,
        canvas: Dict[str, Any],
        scale: int = 80,
        img_width: Optional[int] = None,
        title: Optional[str] = None,
    ):
        self.canvas = canvas
        self.scale = scale
        self.title = title

        max_end = self._compute_max_end()
        content_width = max(int(max_end * scale) + 1, 10)
        self.img_width = img_width if img_width else content_width + MARGIN_LEFT + MARGIN_RIGHT

        timelines = canvas.get("timelines", {})
        threads = canvas.get("threads", {})
        self.lane_objects: Dict[int, dict] = {}

        for tl in timelines.values():
            lid = tl.get("laneId", 0)
            self.lane_objects[lid] = {"color": "#4a4a6a", **tl}
        for th in threads.values():
            lid = th.get("laneId", 1)
            self.lane_objects[lid] = th

        max_lane = max(self.lane_objects.keys(), default=0)
        self.num_lanes = max_lane + 1
        lane_area = self.num_lanes * (LANE_HEIGHT + LANE_GAP)
        self.img_height = MARGIN_TOP + lane_area + MARGIN_BOTTOM

    def _compute_max_end(self) -> float:
        ends: List[float] = [1.0]
        for obj in self.canvas.get("timelines", {}).values():
            ends.append(obj.get("position", 0) + obj.get("duration", 1))
        for obj in self.canvas.get("threads", {}).values():
            ends.append(obj.get("position", 0) + obj.get("duration", 1))
        for obj in self.canvas.get("events", {}).values():
            ends.append(obj.get("position", 0) + obj.get("duration", 1))
        return max(ends)

    def _lane_y(self, lane_id: int) -> int:
        return MARGIN_TOP + lane_id * (LANE_HEIGHT + LANE_GAP)

    def _spine_x(self, position: float) -> int:
        return MARGIN_LEFT + int(position * self.scale)

    def _spine_w(self, duration: float) -> int:
        return max(2, int(duration * self.scale))

    def render_svg(self, overlay_data: Optional[Dict[str, Dict]] = None) -> str:
        """Produce and return a complete SVG document string.

        Parameters
        ----------
        overlay_data : Optional per-event overlay props (from compute_overlay).
        """
        od_map = overlay_data or {}
        W, H = self.img_width, self.img_height
        lines: List[str] = []

        lines.append(
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{W}" height="{H}" '
            f'viewBox="0 0 {W} {H}" '
            f'style="background:{_rgb_css(BG_COLOR)}">'
        )
        lines.append(f'<rect width="{W}" height="{H}" fill="{_rgb_css(BG_COLOR)}"/>')

        # Grid lines
        max_end = self._compute_max_end()
        for i in range(0, int(max_end) + 2):
            x = self._spine_x(i)
            if x > W - MARGIN_RIGHT:
                break
            r, g, b = GRID_COLOR
            lines.append(
                f'<line x1="{x}" y1="{MARGIN_TOP}" x2="{x}" y2="{H - MARGIN_BOTTOM}" '
                f'stroke="rgb({r},{g},{b})" stroke-width="1"/>'
            )
            tr, tg, tb = TICK_COLOR
            lines.append(
                f'<text x="{x + 2}" y="{MARGIN_TOP - 4}" '
                f'font-size="10" fill="rgb({tr},{tg},{tb})">{i}</text>'
            )

        # Title
        if self.title:
            lr, lg, lb = LABEL_FG
            lines.append(
                f'<text x="{MARGIN_LEFT}" y="20" font-size="13" '
                f'font-weight="bold" fill="rgb({lr},{lg},{lb})">'
                f'{_esc(self.title)}</text>'
            )

        # Lane tracks
        for lane_id, obj in self.lane_objects.items():
            y = self._lane_y(lane_id)
            pos = obj.get("position", 0)
            dur = obj.get("duration", 1)
            raw_color = obj.get("color", "#888888")
            try:
                r, g, b = _hex_to_rgb(raw_color)
            except Exception:
                r, g, b = 128, 128, 128
            x = self._spine_x(pos)
            w = self._spine_w(dur)
            alpha = round(THREAD_TRACK_ALPHA / 255, 2)
            lines.append(
                f'<rect x="{x}" y="{y}" width="{w}" height="{LANE_HEIGHT}" '
                f'fill="rgb({r},{g},{b})" fill-opacity="{alpha}"/>'
            )
            lines.append(
                f'<line x1="{x}" y1="{y}" x2="{x + w}" y2="{y}" '
                f'stroke="rgb({r},{g},{b})" stroke-opacity="0.7" stroke-width="1"/>'
            )

        # Build lane color map
        lane_colors: Dict[int, Tuple[int, int, int]] = {}
        for lane_id, obj in self.lane_objects.items():
            try:
                lane_colors[lane_id] = _hex_to_rgb(obj.get("color", "#888888"))
            except Exception:
                lane_colors[lane_id] = (128, 128, 128)

        # Events
        events_sorted = sorted(
            self.canvas.get("events", {}).values(),
            key=lambda e: (e.get("laneId", 0) != 0),
        )
        for event in events_sorted:
            ev_id = event.get("id", "")
            od = od_map.get(ev_id, {})

            lane_id = event.get("laneId", 0)
            y_lane = self._lane_y(lane_id)
            pos = event.get("position", 0)
            dur = event.get("duration", 1)
            is_locked = event.get("isResolved", False)

            # Base color
            base_rgb = lane_colors.get(lane_id, (100, 120, 180))
            r, g, b = _lighten(base_rgb, 1.8)

            # Overlay overrides
            if "fill_rgb" in od:
                r, g, b = od["fill_rgb"]
            opacity: float = od.get("opacity", 1.0)
            ev_alpha = round((EVENT_ALPHA / 255) * opacity, 2)

            x = self._spine_x(pos)
            w = self._spine_w(dur)
            y_ev = y_lane + EVENT_Y_OFFSET
            h_ev = EVENT_HEIGHT

            if "outline_rgb" in od:
                or_, og_, ob_ = od["outline_rgb"]
                stroke = f"rgb({or_},{og_},{ob_})"
            elif is_locked:
                stroke = "#FFD700"
            else:
                stroke = f"rgb({r},{g},{b})"
            stroke_w = od.get("outline_width", 2 if is_locked else 1)

            lines.append(
                f'<rect x="{x}" y="{y_ev}" width="{w}" height="{h_ev}" '
                f'fill="rgb({r},{g},{b})" fill-opacity="{ev_alpha}" '
                f'stroke="{stroke}" stroke-width="{stroke_w}"/>'
            )
            title_text = event.get("title", "")
            if title_text and w > 12:
                max_chars = max(1, (w - 4) // 6)
                label = title_text[:max_chars] + ("…" if len(title_text) > max_chars else "")
                lr, lg, lb = LABEL_FG
                lines.append(
                    f'<text x="{x + 3}" y="{y_ev + 12}" font-size="9" '
                    f'fill="rgb({lr},{lg},{lb})">{_esc(label)}</text>'
                )

            # Badge text (e.g. shot type abbreviation from overlay)
            badge = od.get("badge_text")
            if badge and w > 8:
                bw = len(badge) * 6 + 4
                bh = 9
                bx = x + w - bw - 2
                by = y_ev + h_ev - bh - 1
                if bx >= x:
                    lines.append(
                        f'<rect x="{bx}" y="{by}" width="{bw}" height="{bh}" '
                        f'fill="rgba(0,0,0,0.78)" rx="1"/>'
                    )
                    lines.append(
                        f'<text x="{bx + 2}" y="{by + 8}" font-size="7" '
                        f'fill="rgb(255,255,200)">{_esc(badge)}</text>'
                    )

        # Checkpoints (diamonds)
        for cp in self.canvas.get("checkpoints", {}).values():
            pos = cp.get("position", 0)
            cx = self._spine_x(pos)
            cy = self._lane_y(0) + LANE_HEIGHT // 2
            s = CHECKPOINT_SIZE
            pts = f"{cx},{cy - s} {cx + s},{cy} {cx},{cy + s} {cx - s},{cy}"
            r, g, b = CHECKPOINT_COLOR
            lines.append(
                f'<polygon points="{pts}" fill="rgb({r},{g},{b})" '
                f'stroke="white" stroke-width="1"/>'
            )

        # Lane labels
        for lane_id, obj in sorted(self.lane_objects.items()):
            y = self._lane_y(lane_id) + LANE_HEIGHT // 2 + 4
            name = obj.get("name", obj.get("id", f"Lane {lane_id}"))
            max_chars = (MARGIN_LEFT - 8) // 6
            label = name[:max_chars] if len(name) > max_chars else name
            try:
                r, g, b = _hex_to_rgb(obj.get("color", "#888888"))
            except Exception:
                r, g, b = 160, 160, 180
            lines.append(
                f'<text x="4" y="{y}" font-size="10" fill="rgb({r},{g},{b})">'
                f'{_esc(label)}</text>'
            )

        lines.append("</svg>")
        return "\n".join(lines)


def _rgb_css(rgb: Tuple[int, int, int]) -> str:
    return f"rgb({rgb[0]},{rgb[1]},{rgb[2]})"


# ---------------------------------------------------------------------------
# Sidecar metadata builder
# ---------------------------------------------------------------------------

def build_render_sidecar(
    project_path: Path,
    canvas: Dict[str, Any],
    renderer_width: int,
    renderer_height: int,
    num_lanes: int,
    max_end: float,
    *,
    scope: Optional[str] = None,
    streams: Optional[List[str]] = None,
    status: Optional[str] = None,
    scale: int = 80,
    format: str = "png",
    overlay_mode: Optional[str] = None,
    overlay_matched_count: Optional[int] = None,
) -> dict:
    """
    Build the render metadata sidecar dict.

    This is written as a JSON file alongside the output image when --sidecar is used.
    """
    from datetime import datetime, timezone

    sidecar: dict = {
        "prosadaPath": str(project_path),
        "renderedAt": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "rendererVersion": RENDERER_VERSION,
        "filters": {
            "scope": scope,
            "streams": streams,
            "status": status,
        },
        "renderSettings": {
            "scale": scale,
            "format": format,
        },
        "bounds": {
            "maxEnd": max_end,
            "imgWidth": renderer_width,
            "imgHeight": renderer_height,
            "numLanes": num_lanes,
        },
        "counts": {
            "timelines": len(canvas.get("timelines", {})),
            "threads": len(canvas.get("threads", {})),
            "events": len(canvas.get("events", {})),
            "checkpoints": len(canvas.get("checkpoints", {})),
        },
    }
    if overlay_mode is not None:
        sidecar["overlay"] = {
            "mode": overlay_mode,
            "matchedCount": overlay_matched_count,
        }
    return sidecar


# ---------------------------------------------------------------------------
# Project loader (shared with endpoint + CLI)
# ---------------------------------------------------------------------------

def _load_project(project_path: Path) -> Tuple[Dict, dict, Dict]:
    """
    Load units, manifest, and registries from a prosada project directory.

    Returns (units, manifest, registries_raw)
    Raises FileNotFoundError if the path does not contain manifest.json.
    """
    # Import here to keep top-level imports clean for CLI usage
    import sys
    sys.path.insert(0, str(Path(__file__).parent))
    from persistence.unit_repository import UnitRepository
    from domain.v2_registry import RegistryType

    repo = UnitRepository(project_path)
    manifest = repo.load_manifest()
    units = repo.load_all_units()

    # Build raw registry dicts for color/type lookups
    registries_raw: Dict[str, Any] = {}
    for registry_type in RegistryType:
        rf = repo.load_registry(registry_type)
        if rf is not None:
            registries_raw[registry_type.value] = rf.model_dump(by_alias=True)

    return units, manifest, registries_raw


def _load_and_compose(
    project_path: Path,
) -> Tuple[Dict, Dict, Dict, Dict]:
    """
    Load and compose a project. Returns (units, manifest, registries_raw, canvas).
    Raises FileNotFoundError / ValueError as needed.
    """
    manifest_file = project_path / "manifest.json"
    if not manifest_file.exists():
        raise FileNotFoundError(f"No manifest.json in {project_path}")

    units, manifest, registries_raw = _load_project(project_path)
    if not units:
        raise ValueError(f"No units found in {project_path / 'units'}")

    from services.canvas_layout_composer import CanvasLayoutComposer
    canvas = CanvasLayoutComposer.compose(units, manifest, registries_raw)
    return units, manifest, registries_raw, canvas


def render_project(
    project_path: Path,
    *,
    scope: Optional[str] = None,
    streams: Optional[List[str]] = None,
    status: Optional[str] = None,
    scale: int = 80,
    img_width: Optional[int] = None,
    title: Optional[str] = None,
) -> Image.Image:
    """
    Full render pipeline → PNG (PIL Image).

    Raises FileNotFoundError / ValueError on invalid projects.
    """
    units, manifest, registries_raw, canvas = _load_and_compose(project_path)
    canvas = _apply_canvas_filters(canvas, units, scope, streams, status)
    renderer = TimelineRenderer(canvas, scale=scale, img_width=img_width, title=title)
    return renderer.render()


def render_project_svg(
    project_path: Path,
    *,
    scope: Optional[str] = None,
    streams: Optional[List[str]] = None,
    status: Optional[str] = None,
    scale: int = 80,
    img_width: Optional[int] = None,
    title: Optional[str] = None,
) -> str:
    """
    Full render pipeline → SVG (str).

    Raises FileNotFoundError / ValueError on invalid projects.
    """
    units, manifest, registries_raw, canvas = _load_and_compose(project_path)
    canvas = _apply_canvas_filters(canvas, units, scope, streams, status)
    renderer = SVGTimelineRenderer(canvas, scale=scale, img_width=img_width, title=title)
    return renderer.render_svg()


def render_project_with_sidecar(
    project_path: Path,
    *,
    format: str = "png",
    scope: Optional[str] = None,
    streams: Optional[List[str]] = None,
    status: Optional[str] = None,
    scale: int = 80,
    img_width: Optional[int] = None,
    title: Optional[str] = None,
) -> Tuple[Any, dict]:
    """
    Full render pipeline returning (output, sidecar_dict).

    output is PIL.Image for format="png", str for format="svg".
    sidecar_dict is always a JSON-serialisable dict.
    """
    units, manifest, registries_raw, canvas = _load_and_compose(project_path)
    canvas = _apply_canvas_filters(canvas, units, scope, streams, status)

    if format == "svg":
        r = SVGTimelineRenderer(canvas, scale=scale, img_width=img_width, title=title)
        output = r.render_svg()
        w, h, nl = r.img_width, r.img_height, r.num_lanes
        max_end = r._compute_max_end()
    else:
        r = TimelineRenderer(canvas, scale=scale, img_width=img_width, title=title)
        output = r.render()
        w, h, nl = r.img_width, r.img_height, r.num_lanes
        max_end = r._compute_max_end()

    sidecar = build_render_sidecar(
        project_path, canvas, w, h, nl, max_end,
        scope=scope, streams=streams, status=status,
        scale=scale, format=format,
    )
    return output, sidecar


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="render_timeline",
        description="Render a ProsAda project's timeline topology to PNG or SVG.",
    )
    p.add_argument(
        "--project", required=True,
        help="Path to prosada project directory (contains manifest.json + units/).",
    )
    p.add_argument(
        "--out", default="timeline.png",
        help="Output file path (default: timeline.png).",
    )
    p.add_argument(
        "--format", default="png", choices=["png", "svg"],
        help="Output format: png (default) or svg.",
    )
    p.add_argument(
        "--sidecar", action="store_true",
        help="Write a JSON metadata sidecar alongside --out.",
    )
    p.add_argument(
        "--scope", default=None,
        help="Only render events reachable from this unitId.",
    )
    p.add_argument(
        "--streams", default=None,
        help="Comma-separated stream/thread IDs to include (default: all).",
    )
    p.add_argument(
        "--status", default=None, choices=["draft", "review", "locked"],
        help="Only include events with this status.",
    )
    p.add_argument(
        "--scale", type=int, default=80,
        help="Pixels per spine logical unit (default: 80).",
    )
    p.add_argument(
        "--width", type=int, default=None, dest="img_width",
        help="Total image width in pixels (auto-sized if omitted).",
    )
    p.add_argument(
        "--title", default=None,
        help="Optional title text overlay on the image.",
    )
    # Overlay flags (Burst 12 + 13)
    p.add_argument(
        "--overlay", default=None, choices=list(_OVERLAY_REGISTRY),
        help=(
            "Overlay mode: semantic (entity refs) | status (narrative status) | "
            "mood (presentation moodTags) | shot (presentation shotType)."
        ),
    )
    p.add_argument(
        "--semantic-kind", default=None, dest="semantic_kind",
        help="Semantic ref kind filter for --overlay semantic (char/concept/symbol/location/artifact/thread).",
    )
    p.add_argument(
        "--semantic-id", default=None, dest="semantic_id",
        help="Entity ID filter for --overlay semantic (e.g. joey-valdez).",
    )
    p.add_argument(
        "--projection-json", default=None, dest="projection_json",
        help="Path to write the full projection payload as JSON.",
    )
    # Prompt export flag (Burst 13)
    p.add_argument(
        "--prompt-export", default=None, dest="prompt_export",
        help="Path to write prompt packet export JSON (storyboard-basic profile by default).",
    )
    p.add_argument(
        "--prompt-profile", default="storyboard-basic", dest="prompt_profile",
        choices=["storyboard-basic", "image-concept", "narrative-summary"],
        help="Prompt packet export profile (default: storyboard-basic).",
    )
    return p


def main(argv: Optional[List[str]] = None) -> int:
    import json as _json

    parser = _build_parser()
    args = parser.parse_args(argv)

    project_path = Path(args.project).expanduser().resolve()
    out_path = Path(args.out).expanduser().resolve()
    fmt = args.format.lower()

    streams: Optional[List[str]] = None
    if args.streams:
        streams = [s.strip() for s in args.streams.split(",") if s.strip()]

    needs_projection = bool(args.projection_json or args.overlay or args.prompt_export)

    # Always load project explicitly so overlay code can access canvas
    try:
        units, manifest, registries_raw, canvas_raw = _load_and_compose(project_path)
    except FileNotFoundError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    canvas = _apply_canvas_filters(canvas_raw, units, args.scope, streams, args.status)

    # Build projection payload if needed
    projection: Optional[Dict] = None
    if needs_projection:
        try:
            from services.projection_builder import build_projection
            projection = build_projection(
                project_path,
                scope=args.scope,
                streams=streams,
                status=args.status,
                semantic_kind=args.semantic_kind,
                semantic_entity_id=args.semantic_id,
            )
        except Exception as exc:
            print(f"Warning: projection build failed: {exc}", file=sys.stderr)

    # Write prompt packet export if requested
    if args.prompt_export and projection is not None:
        try:
            from services.prompt_exporter import export_prompt_packets
            packets = export_prompt_packets(
                project_path,
                profile=args.prompt_profile,
                scope=args.scope,
                streams=streams,
                status=args.status,
            )
            pe_out = Path(args.prompt_export).expanduser().resolve()
            pe_out.parent.mkdir(parents=True, exist_ok=True)
            pe_out.write_text(_json.dumps(packets, indent=2), encoding="utf-8")
            print(f"Saved prompt export: {pe_out}  ({packets['summary']['packetCount']} packets)")
        except Exception as exc:
            print(f"Warning: prompt export failed: {exc}", file=sys.stderr)

    # Write projection JSON if requested
    if args.projection_json and projection is not None:
        proj_out = Path(args.projection_json).expanduser().resolve()
        proj_out.parent.mkdir(parents=True, exist_ok=True)
        proj_out.write_text(_json.dumps(projection, indent=2), encoding="utf-8")
        print(f"Saved projection JSON: {proj_out}")

    # Compute overlay data
    overlay_data: Optional[Dict[str, Dict]] = None
    if args.overlay:
        if projection is not None:
            overlay_data = compute_overlay(
                args.overlay,
                canvas,
                projection,
                semantic_kind=args.semantic_kind,
                semantic_entity_id=args.semantic_id,
            )
        else:
            print(
                f"Warning: --overlay {args.overlay} requested but projection build failed; "
                "rendering without overlay.",
                file=sys.stderr,
            )

    render_kwargs: Dict[str, Any] = dict(
        scale=args.scale,
        img_width=args.img_width,
        title=args.title or str(project_path.name),
    )

    # Render
    try:
        if fmt == "svg":
            r_svg = SVGTimelineRenderer(canvas, **render_kwargs)
            output_svg = r_svg.render_svg(overlay_data=overlay_data)
            r_width, r_height, r_lanes = r_svg.img_width, r_svg.img_height, r_svg.num_lanes
            r_max_end = r_svg._compute_max_end()
        else:
            r_png = TimelineRenderer(canvas, **render_kwargs)
            output_png = r_png.render(overlay_data=overlay_data)
            r_width, r_height, r_lanes = r_png.img_width, r_png.img_height, r_png.num_lanes
            r_max_end = r_png._compute_max_end()
    except Exception as exc:
        print(f"Error: rendering failed: {exc}", file=sys.stderr)
        return 2

    # Sidecar
    sidecar: Optional[dict] = None
    if args.sidecar:
        overlay_matched = len([k for k, v in (overlay_data or {}).items() if v.get("opacity", 1.0) >= 1.0 and "fill_rgb" not in v]) if overlay_data else None
        sidecar = build_render_sidecar(
            project_path, canvas, r_width, r_height, r_lanes, r_max_end,
            scope=args.scope, streams=streams, status=args.status,
            scale=args.scale, format=fmt,
            overlay_mode=args.overlay,
            overlay_matched_count=len(overlay_data) if overlay_data else None,
        )

    # Write output
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if fmt == "svg":
        out_path.write_text(output_svg, encoding="utf-8")
        print(f"Saved SVG: {out_path}")
    else:
        output_png.save(str(out_path), "PNG")
        print(f"Saved PNG: {out_path}  ({output_png.width}×{output_png.height}px)")

    if sidecar:
        sidecar_path = out_path.with_suffix(".json")
        sidecar_path.write_text(_json.dumps(sidecar, indent=2), encoding="utf-8")
        print(f"Saved sidecar: {sidecar_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
